version: '3'

services:
  app:
    image: php:7.4-apache
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_password
      MYSQL_ROOT_PASSWORD: your_database_root_password
    ports:
      - "3306:3306"